title: Product
icon: tag

navigation:
  status: all
  sortBy: title asc

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          name:
            label: Name
            type: text
            required: true

          availability_status:
            label: Status
            type: select
            default: available
            options:
              - coming soon
              - sold out
              - available
            width: 1/2

          # item_reloved:
          #   label: Reloved?
          #   type: toggle
          #   default: false
          #   width: 1/4

          Price:
            label: Price in CHF
            type: number
            width: 1/2
            required: true

          Identifier:
            label: Identifier
            type: text
            width: 1/2
            required: true

          Weight:
            label: Weight
            type: number
            width: 1/2

          Sizes:
            label: Sizes
            type: multiselect
            min: 1
            options: query
            query: page.parent.sizes.split
            width: 1/2

          Category:
            label: Category
            type: multiselect
            max: 1
            options: query
            query: page.parent.categories.split

          Description:
            label: Description
            type: textarea
            size: small

          Custom_fields:
            label: Custom Fields
            type: structure
            fields:
              title:
                label: Title
                type: text
              cf_content:
                label: Content
                type: textarea

          primaryimage:
            label: Main Image
            type: files
            layout: cards
            size: small
            image:
              background: white
            multiple: false
            required: true
            width: 1/2

          secondaryimage:
            label: Second Image
            type: files
            layout: cards
            size: small
            image:
              background: white
            multiple: false
            width: 1/2

  - width: 1/2
    sections:
      Images:
        headline: Gallery
        type: files
        layout: cards
        image:
          ratio: 4/5
          cover: true
