title: Project
icon: folder

navigation:
  status: all
  sortBy: title asc

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          # projecttitle:
          #   label: Project Title
          #   type: text
          #   required: true
          # subtitle:
          #   label: Sub Title
          #   type: text
          # year:
          #   label: Year
          #   type: number
          # location:
          #   label: Location
          #   type: text
          coverimage:
            label: Cover Image
            type: files
            layout: cards
            size: small
            multiple: false
            image:
              cover: false
              back: grey
            width: 1/2
          secondaryimage:
            label: Secondary Image
            type: files
            layout: cards
            size: small
            multiple: false
            image:
              back: grey
            width: 1/2
          layout:
            label: Content
            type: layout
            fieldsets:
              - heading
              - text
              - gallery
              - video

  - width: 1/2
    sections:
      files:
        headline: Files
        type: files
        layout: cards
        image:
          back: grey
