columns:
  main:
    width: 1/1
    sections:
      info:
        type: fields
        fields:
          projecttitle:
            label: Project Title
            type: text
            width: 1/4
            required: true
          subtitle:
            label: Sub Title
            type: text
            width: 1/4
          year:
            label: Year
            type: number
            min: 2000
            default: 2018
            width: 1/4
          cover:
            label: Cover Project?
            type: toggle
            text:
              - "no"
              - "yes"
            width: 1/4
          projectinfo:
            label: Project description
            type: textarea
            size: small
            width: 1/1
            required: true
          layout:
            type: layout
            width: 1/2
            layouts:
              - "1/1"
            fieldsets:
              - gallery

  sidebar:
    width: 1/1
    sections:
      published:
        headline: uploaded images
        type: files
        status: listed
        layout: cards
        size: small
        image:
          cover: false
          ratio: 1/1.5
          back: black
