title: Site
tabs:
  startscreen:
      label: Start Screen
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            layout: list
            size: medium
            status: listed

          not_listed:
            headline: Not listed
            type: pages
            layout: list
            size: medium
            status: unlisted

          drafts:
            headline: Drafts
            type: pages
            layout: list
            size: medium
            status: drafts
            
      - width: 1/2
        fields:
          startscreen:
            label: Start Screen
            type: headline
            numbered: false
          button_text:
            label: Button Text
            type: text
            required: true
          futured:
            label: Linked Page
            type: pages
            multiple: false
          background:
            label: Background
            type: files
            layout: cards
            size: medium
            image:
              background: white
            multiple: false
          background_mobile:
            label: Background mobile
            type: files
            layout: cards
            size: medium
            image:
              background: white
            multiple: false

      - width: 1/1
        sections:
          files:
            type: files
            layout: list
            size: medium
            status: listed

  infobox:
      label:
      sections:
    fields:
      contact_section:
        label: Contact
        type: headline
        numbered: false
      customfield_title:
        label: Custom Field Title
        type: text
      customfield:
        label: Custom Field Content
        type: textarea
      address:
        label: Address block
        type: textarea
      mail:
        label: Mail
        type: email
      phone:
        label: Phone
        type: tel
      instagram:
        label: Instagram
        type: url
        width: 1/2
      instagram_handle:
        label: Instagram handle
        type: text
        width: 1/2
      newsletter:
        label: Newsletter
        type: url
      metaDescription:
        label: Meta Description
        type: textarea
        size: small
        buttons: false
        help: "This is the text google shows in the resulst. Meta descriptions can be any length, but Google generally truncates snippets to ~155–160 characters. Keep meta descriptions long enough that they're sufficiently descriptive, some sources recommend descriptions between 50–160 characters."
